#!/usr/bin/env bash
#install and test nginx on your web-01 server
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www
sudo echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
