#!/usr/bin/env bash
#Install and configure HAproxy on lb-01 server.

sudo apt-get install software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-1.8
sudo apt-get update
sudo apt-get install haproxy=1.8.\*

echo "ENABLED=1" >> /etc/default/haproxy

echo -e "
frontend load_balancer
    bind *:80
    mode http
    default_backend webserver
backend webserver
    balance roundrobin
    server 1423-web-01 34.75.103.17:80 check
    server 1423-web-02 34.75.105.30:80 check
" >> /etc/haproxy/haproxy.cfg
service haproxy start
