#!/usr/bin/env bash
#Install and configure HAproxy on lb-01 server.

apt-get install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get update
apt-get -y install haproxy=2.0.\*

echo "ENABLED=1" >> /etc/default/haproxy

echo "
frontend load_balancer
    bind *:80
    mode http
    default_backend webserver
backend webserver
    balance roundrobin
    server 1423-web-01 34.75.103.17:80 check
    server 1423-web-02 34.75.105.30:80 check
" >> /etc/haproxy/haproxy.cfg
service haproxy start
