#!/usr/bin/env bash
# configures the container to fit the above requirements
pkill nginx
chown nginx:nginx /etc/nginx/nginx.conf
chmod 600 /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx service nginx start
